name: build-image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t ghcr.io/41tair/ngx_http_proxy_connect_module/nginx:1.19.3 .
      - name: login to github package docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: 41tair
          password: ${{ secrets.GITHUBTOKEN }}
      - name: push to github package
        run: |
          docker push ghcr.io/41tair/ngx_http_proxy_connect_module/nginx:1.19.3
