name: build-image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t ghcr.io/41tair/ngx_http_proxy_connect_module/nginx:1.19.3 .
      - name: push to github package
        with:
          token: ${{ secrets.GITHUBTOKEN }}
        env:
          token: ${{ secrets.GITHUBTOKEN }}
        run: |
          echo "$token" |docker login https://ghcr.io -u 41tair --password-stdin
          docker push ghcr.io/41tair/ngx_http_proxy_connect_module/nginx:1.19.3
